name: CMake Build

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v2
      with:
        cmake-version: '3.21'  # Change this to your desired CMake version

    - name: Configure
      run: cmake -Bbuild

    - name: Build
      run: cmake --build build
